package com.school.application.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import com.school.application.dtos.Module;
import com.school.application.dtos.Student;

public interface ModuleRepository extends JpaRepository<Module, Long> {

	// Method names define the 'SQL' that is generated by spring.
	List<Module> findById(Optional<Integer> id);

	Optional<Module> findByModuleCode(String moduleCode);

}
